# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Scripts.\lab10q2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 268)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_number = QtWidgets.QLabel(self.centralwidget)
        self.label_number.setMinimumSize(QtCore.QSize(131, 61))
        self.label_number.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_number.setFont(font)
        self.label_number.setObjectName("label_number")
        self.verticalLayout_2.addWidget(self.label_number)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_points = QtWidgets.QLabel(self.centralwidget)
        self.label_points.setMinimumSize(QtCore.QSize(131, 61))
        self.label_points.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_points.setFont(font)
        self.label_points.setTextFormat(QtCore.Qt.PlainText)
        self.label_points.setObjectName("label_points")
        self.verticalLayout.addWidget(self.label_points)
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setMinimumSize(QtCore.QSize(81, 61))
        self.label_0.setMaximumSize(QtCore.QSize(81, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_0.setFont(font)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setObjectName("label_0")
        self.verticalLayout.addWidget(self.label_0)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout.addWidget(self.pushButton_confirm)
        self.pushButton_nextnumber = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nextnumber.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_nextnumber.setObjectName("pushButton_nextnumber")
        self.horizontalLayout.addWidget(self.pushButton_nextnumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.points=0
        self.pushButton_confirm.clicked.connect(self.buttonConfirm)
        self.pushButton_nextnumber.clicked.connect(self.buttonClicked)
        self.comboBox.activated[str].connect(self.onActivated)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_number.setText(_translate("MainWindow", "Number"))
        self.label_points.setText(_translate("MainWindow", "Points"))
        self.label_0.setText(_translate("MainWindow", "0"))
        self.comboBox.setItemText(0, _translate("MainWindow", "One"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Two"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Three"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Four"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Five"))
        self.pushButton_confirm.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_nextnumber.setText(_translate("MainWindow", "Next Number"))

    def onActivated(self,text):
        self.choice=text
        print(self.choice) 
        
    def buttonClicked(self):
        self.num=random.randint(1,5)
        print(self.num)
        self.label_number.setText(str(self.num))
    
    def buttonConfirm(self):
        if self.num==1 and self.choice=="One":
            self.points += 10
        elif self.num==2 and self.choice=="Two": 
            self.points += 10
        elif self.num==3 and self.choice=="Three":  
            self.points += 10
        elif self.num==4 and self.choice=="Four":   
            self.points += 10
        elif self.num==5 and self.choice=="Five":   
            self.points += 10
            
        self.label_0.setText(str(self.points))   
        print(self.points)
        