# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Scripts.\2024_q2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generate.setMinimumSize(QtCore.QSize(461, 31))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.verticalLayout.addWidget(self.pushButton_generate)
        self.label_numbers = QtWidgets.QLabel(self.centralwidget)
        self.label_numbers.setMinimumSize(QtCore.QSize(461, 16))
        self.label_numbers.setObjectName("label_numbers")
        self.verticalLayout.addWidget(self.label_numbers)
        self.textEdit_numbers = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_numbers.setMinimumSize(QtCore.QSize(461, 111))
        self.textEdit_numbers.setObjectName("textEdit_numbers")
        self.verticalLayout.addWidget(self.textEdit_numbers)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_max = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_max.setEnabled(False)
        self.radioButton_max.setMinimumSize(QtCore.QSize(91, 21))
        self.radioButton_max.setObjectName("radioButton_max")
        self.horizontalLayout.addWidget(self.radioButton_max)
        self.radioButton_min = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_min.setEnabled(False)
        self.radioButton_min.setMinimumSize(QtCore.QSize(91, 21))
        self.radioButton_min.setObjectName("radioButton_min")
        self.horizontalLayout.addWidget(self.radioButton_min)
        self.radioButton_sort = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_sort.setEnabled(False)
        self.radioButton_sort.setMinimumSize(QtCore.QSize(91, 21))
        self.radioButton_sort.setObjectName("radioButton_sort")
        self.horizontalLayout.addWidget(self.radioButton_sort)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(False)
        self.comboBox.setMinimumSize(QtCore.QSize(91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.radioButton_reverse = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_reverse.setEnabled(False)
        self.radioButton_reverse.setMinimumSize(QtCore.QSize(91, 21))
        self.radioButton_reverse.setObjectName("radioButton_reverse")
        self.horizontalLayout.addWidget(self.radioButton_reverse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setMinimumSize(QtCore.QSize(461, 16))
        self.label_Result.setObjectName("label_Result")
        self.verticalLayout.addWidget(self.label_Result)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setMinimumSize(QtCore.QSize(461, 111))
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout.addWidget(self.textEdit_result)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setMinimumSize(QtCore.QSize(461, 16))
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_generate.setText(_translate("MainWindow", "Generate Numbers"))
        self.label_numbers.setText(_translate("MainWindow", "Numbers"))
        self.textEdit_numbers.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">No number</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_max.setText(_translate("MainWindow", "Max"))
        self.radioButton_min.setText(_translate("MainWindow", "Min"))
        self.radioButton_sort.setText(_translate("MainWindow", "Sort"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Ascending"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Descending"))
        self.radioButton_reverse.setText(_translate("MainWindow", "Reverse"))
        self.label_Result.setText(_translate("MainWindow", "Result"))
        self.textEdit_result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">No result</p></body></html>"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        
    
        